services:
  - type: worker
    name: telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_runner.py"
    envVars:
      - key: BOT_TOKEN
        sync: false  # set it manually in Render dashboard
    disk:
      name: bot-data
      mountPath: /var/data
      sizeGB: 1
